In [0]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression


In [0]:
steps=[("standard_scaler",StandardScaler()),("classifier",LogisticRegression())]
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [0]:
pipe=Pipeline(steps)
from sklearn import set_config
set_config(display="diagram")
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [0]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000)
x.shape

(1000, 20)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)


In [0]:
x_train

array([[ 6.08164413e-01,  1.22280932e+00,  1.02796549e+00, ...,
         7.67455938e-01,  2.14483297e-01, -6.69803860e-01],
       [ 1.02674355e+00,  1.36159747e+00,  5.15375477e-01, ...,
        -2.90025755e-02, -1.55916092e+00, -1.10905189e+00],
       [-7.91675439e-04, -2.22471083e-01,  4.38913488e-01, ...,
        -1.34121461e+00,  3.31347121e-02, -2.24613025e-01],
       ...,
       [ 4.42439982e-01,  2.23187317e+00,  1.60032466e+00, ...,
        -7.22474025e-01, -1.11092832e+00,  1.67433179e+00],
       [ 1.95357641e-01,  4.34711591e-01, -9.86345510e-01, ...,
         3.77751500e-01, -2.73035411e-01, -5.13134280e-01],
       [ 5.25011098e-01,  1.91426230e-01,  1.54702476e+00, ...,
         2.26847079e-01,  1.85770585e+00, -8.31623911e-01]])

In [0]:
pipe.fit(x_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),('classifier',LogisticRegression())])
y_pred=pipe.predict(x_test)
y_pred

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [0]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [0]:
steps=[("scaling",StandardScaler()),("PCA",PCA(n_components=3)),("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(x_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',PCA(n_components=3)),('SVC', SVC())])
pipe2.predict(x_test)

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,

In [0]:
from sklearn.impute import SimpleImputer

In [0]:
import numpy as np
numeric_processor=Pipeline(
    
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
("scaler",StandardScaler())])
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),('scaler', StandardScaler())])

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [0]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    
steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),("onehot",OneHotEncoder(handle_unknown="ignore"))])
categorical_processor
Pipeline(steps=[('imputation_consaatnt',SimpleImputer(fill_value='missing',strategy='constant')),('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consaatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [0]:
 categorical_processor
 Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', 
strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])
 ## combine processing technqiues
 from sklearn.compose import ColumnTransformer
 preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]
 )
 preprocessor
 ColumnTransformer(transformers=[('categorical',
                                 
Pipeline(steps=[('imputation_consatnt',
                                                  
SimpleImputer(fill_value='missing',
                                                                
strategy='constant')),
                                                 ('onehot',
                                                  
OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', 
StandardScaler())]),
                                 ['age', 'height'])])
 from sklearn.pipeline import make_pipeline
 pipe=make_pipeline(preprocessor,LogisticRegression())
 pipe
 Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  
Pipeline(steps=[('imputation_consatnt',
                                                                   
SimpleImputer(fill_value='missing',
                                                                       
strategy='constant')),
                                                                  
('onehot',
                                                                   
OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  
Pipeline(steps=[('imputation_mean',
                                                                   
SimpleImputer()),
                                                                  
('scaler',
                                                                   
StandardScaler())]),
                                                  ['age', 
'height'])])),
                ('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])